from config import MQTT_TOPIC_PREFIX

SENSOR_TOPIC = f"{MQTT_TOPIC_PREFIX}/sensor"
TEMPERATURE_TOPIC = f"{SENSOR_TOPIC}/temperature"
HUMIDITY_TOPIC = f"{SENSOR_TOPIC}/humidity"
DEVICE_STATE_TOPIC = f"{MQTT_TOPIC_PREFIX}/device-state"
COMMAND_TOPIC = f"{MQTT_TOPIC_PREFIX}/commands"
STATUS_TOPIC = f"{MQTT_TOPIC_PREFIX}/status"
