from config import MQTT_TOPIC_PREFIX

SENSOR_TOPIC = f"{MQTT_TOPIC_PREFIX}/sensor"
DEVICE_STATE_TOPIC = f"{MQTT_TOPIC_PREFIX}/device-state"
COMMAND_TOPIC = f"{MQTT_TOPIC_PREFIX}/commands"
STATUS_TOPIC = f"{MQTT_TOPIC_PREFIX}/status"
